AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "Find a Tutor"

Resources:
  FindATutorLambdaLayer:
    Type: "AWS::Serverless::LayerVersion"
    Properties:
      LayerName: "FindATutor"
      Description: "Find a Tutor layer for lambda"
      ContentUri: "../find-a-tutor/layer"
      CompatibleRuntimes:
        - python3.8
      LicenseInfo: MIT
      RetentionPolicy: Retain
