AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "Find a Tutor"

Globals:
  Function:
    Runtime: "python3.8"
    MemorySize: 128
    Timeout: 300
    Environment:
      Variables:
        LOG_LEVEL: "INFO"
        POWERTOOLS_SERVICE_NAME: "find-a-tutor"

Resources:
  FindATutorLambdaLayer:
    Type: "AWS::Serverless::LayerVersion"
    Properties:
      LayerName: "FindATutor"
      Description: "Find a Tutor layer for lambda"
      ContentUri: "../find-a-tutor/layer"
      CompatibleRuntimes:
        - python3.8
      LicenseInfo: MIT
      RetentionPolicy: Retain
